### PR TITLE
[Fix] Remove filename from mounted uploader after model save

### PR DESCRIPTION
**Pull request by pharlez**
Carrierwave uses that field to check if something is assigned to
the instance's mounted attribute, so it would to have to update
the record. Here we remove the original filename that is left behind
after a model.save so a subsequent, unrelated save on the same
instance will not trigger an update of the column where the uploader
is mounted on.

### CODE REVIEW

**Comment by ctrochalakis** [comment]
@pharlez Αυτό είναι bug του carrierwave ή του τρόπου που που χρησιμοποιούμε εμείς το `original_filename`?

αν ισχύει το 2ο, γιατι δεν βάζουμε αυτό το patch στο mixin μας;

**Comment by pharlez** [comment]
@ctrochalakis this goes hand-in-hand with https://github.com/skroutz/carrierwave/commit/a8b75f185b86ec668876c86a16d060ae5828ae88

It's a bug that emerges from overriding `filename` to add timestamp etc in which case carrierwave does not properly clean up assigned attributes, resulting in unintended behaviour

**Comment by alup** [comment]
+1

**Comment by avgerin0s** [comment]
:+1: LGTM

**Pull request merged**
