### PR TITLE
Truncate long filename before saving tempfile on cache!

### PR DESCRIPTION
**Pull request by pharlez**
Reinstates patch by @vrinek that got rejected on upgrade to v0.10
Avoids Errno::ENAMETOOLONG exception that mostly occurs when saving
a remote image with greek letters in the URL

### CODE REVIEW

**Comment by avgerin0s** [comment]
Don't we have a module for that in the application?

**Comment by avgerin0s** [comment]
Could we avoid this with `URI.decode` the greek encoded characters?

**Comment by vrinek** [comment]
Don't forget the tests.

**Comment by alup** [comment]
:)

**Pull request closed without merging**
